name: Add team label

on:
  pull_request:
    types:
      - opened

jobs:
  add-team-label:
    uses: metamask/github-tools/.github/workflows/add-team-label.yml@MRCM-8-AutomaticLabelingWorkflow
    secrets:
      TEAM_LABEL_TOKEN: ${{ secrets.TEAM_LABEL_TOKEN }}
